CREATE DATABASE IF NOT EXISTS concesionariodb;
USE concesionariodb;

CREATE TABLE TIPOS_COMBUSTIBLE (
    TipoCombustibleID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE TIPOS_TRANSMISION (
    TipoTransmisionID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE ESTADOS_VEHICULO (
    EstadoID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE VEHICULOS (
    VIN VARCHAR(50) PRIMARY KEY,
    Marca VARCHAR(50) NOT NULL,
    Modelo VARCHAR(50) NOT NULL,
    Anio INT NOT NULL,
    Precio DECIMAL(10,2) NOT NULL,
    Color VARCHAR(30) NOT NULL,
    TipoCombustibleID INT,
    TipoTransmisionID INT,
    EstadoID INT,
    Disponible BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (TipoCombustibleID) REFERENCES TIPOS_COMBUSTIBLE(TipoCombustibleID),
    FOREIGN KEY (TipoTransmisionID) REFERENCES TIPOS_TRANSMISION(TipoTransmisionID),
    FOREIGN KEY (EstadoID) REFERENCES ESTADOS_VEHICULO(EstadoID)
);

CREATE TABLE PERSONAS_FISICAS (
    PersonaFisicaID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    Telefono VARCHAR(20),
    CorreoElectronico VARCHAR(100) UNIQUE NOT NULL,
    Direccion TEXT
);

CREATE TABLE CLIENTES (
    ClienteID INT AUTO_INCREMENT PRIMARY KEY,
    PersonaFisicaID INT UNIQUE,
    FOREIGN KEY (PersonaFisicaID) REFERENCES PERSONAS_FISICAS(PersonaFisicaID)
);

CREATE TABLE EMPLEADOS (
    EmpleadoID INT AUTO_INCREMENT PRIMARY KEY,
    PersonaFisicaID INT UNIQUE,
    NumeroEmpleado VARCHAR(50) UNIQUE NOT NULL,
    FechaContratacion DATE NOT NULL,
    FOREIGN KEY (PersonaFisicaID) REFERENCES PERSONAS_FISICAS(PersonaFisicaID)
);

CREATE TABLE METODOS_PAGO (
    MetodoPagoID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE VENTAS (
    VentaID INT AUTO_INCREMENT PRIMARY KEY,
    ClienteID INT,
    EmpleadoID INT,
    FechaVenta DATE NOT NULL,
    Total DECIMAL(10,2) NOT NULL,
    MetodoPagoID INT,
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID),
    FOREIGN KEY (EmpleadoID) REFERENCES EMPLEADOS(EmpleadoID),
    FOREIGN KEY (MetodoPagoID) REFERENCES METODOS_PAGO(MetodoPagoID)
);

CREATE TABLE DETALLE_VENTAS (
    DetalleID INT AUTO_INCREMENT PRIMARY KEY,
    VentaID INT,
    VIN VARCHAR(50),
    PrecioVenta DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (VentaID) REFERENCES VENTAS(VentaID),
    FOREIGN KEY (VIN) REFERENCES VEHICULOS(VIN)
);

CREATE TABLE TIPOS_SERVICIO (
    TipoServicioID INT AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE SERVICIOS_MANTENIMIENTO (
    ServicioID INT AUTO_INCREMENT PRIMARY KEY,
    VIN VARCHAR(50),
    ClienteID INT NULL,
    TipoServicioID INT,
    Costo DECIMAL(10,2) NOT NULL,
    FechaServicio DATE NOT NULL,
    Descripcion TEXT,
    FOREIGN KEY (VIN) REFERENCES VEHICULOS(VIN),
    FOREIGN KEY (ClienteID) REFERENCES CLIENTES(ClienteID),
    FOREIGN KEY (TipoServicioID) REFERENCES TIPOS_SERVICIO(TipoServicioID)
);
